### PR TITLE
Configure connections via application and remove GenServer wrapper

### PR DESCRIPTION
**Pull request by lastcanal**
Hello, @solatis and @kelostrada. I have done some merging of various forks and managed to get a collection of changes to include in this PR.  

I have also changed the configuration to be handled at the application level so it is not longer required to start a dedicated GenServer process to send RPC requests.  This also removes a blocking bottle neck that would form in the system if many requests were being routed through a single process. 

Instead of calling `Gold.start_link(my_node_config)` and tracking the PID, you set the configuration in config/config.exs and use the configuration name directly

Under the hood this calls Application.get_env/2 which is fast enough.

```elixir
config :gold, :my_node, [
  hostname: "localhost",
  port: 18332,
  user: "bitcoinrpc",
  password: "changeme"
]
```

```elixir
Gold.getinfo(:my_node)
```

This PR builds off @kelostrada fork: https://github.com/solatis/gold/pull/1 and also includes @denis4net’s commits from https://github.com/solatis/gold/pull/4

To see a diff between my changes and @kelostrada’s changes take a look here: https://github.com/kelostrada/gold/compare/master...lastcanal:master

### CODE REVIEW

**Comment by kelostrada** [comment]
This looks pretty good, you did some heavy work I was intending to do some day myself... so big thumbs up to you! I will try to contact @solatis about hex.pm account to publish this, but I will merge this probably on weekend when I find some time to test everything! Thanks!

**Comment by kelostrada** [comment]
One thing I don't like about this approach (Application instead of GenServer) is that you cannot easily add new connections to `bitcoind`s (during runtime). I'll think about this feature in the future though ;)

**Comment by lastcanal** [comment]
It would be possible to add new connections using [`Application.set_env/4`](https://hexdocs.pm/elixir/Application.html#put_env/4). I could add a helper method that allows users to 'register' their configuration with a 'name'

```elixir
{:ok, :node1} = Gold.register(:node1, config)
```
We could even alias start_link and return the registered name in place of a spawned pid, keeping the same api as before.

**Comment by kelostrada** [comment]
That would be great! Although I'm not sure we should keep the same api - `start_link` suggests usage of `GenServer` while there is no such thing in the background happening.

**Pull request merged**
